services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./app/certs:/app/certs
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: kumon
      POSTGRES_PASSWORD: kumon123
      POSTGRES_DB: kumon_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
