"""cria todas as tabelas - Fase 2

Revision ID: 51b8d3c72d61
Revises: 
Create Date: 2026-03-13 15:35:45.917052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51b8d3c72d61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('data_matricula', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ativo', 'inativo', 'concluinte', name='status_aluno'), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias_financeiras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('receita', 'despesa', name='tipo_categoria'), nullable=False),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.Column('eh_retirada_pessoal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracoes_whatsapp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provedor', sa.Enum('evolution_api', 'z_api', name='provedor_whatsapp'), nullable=False),
    sa.Column('api_url', sa.Text(), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('numero_instancia', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('abreviacao', sa.String(length=5), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsaveis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('telefone_whatsapp', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('profissao', sa.String(length=150), nullable=True),
    sa.Column('empresa', sa.String(length=150), nullable=True),
    sa.Column('preferencia_boleto', sa.Enum('digital', 'impresso', name='preferencia_boleto'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('slots_horario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dia_semana', sa.Enum('seg', 'ter', 'qua', 'qui', 'sex', 'sab', name='dia_semana'), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates_documentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('contrato_matricula', 'termo_rescisao', 'outro', name='tipo_template'), nullable=False),
    sa.Column('conteudo_html', sa.Text(), nullable=False),
    sa.Column('variaveis_disponiveis', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alunos_responsaveis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('responsavel_id', sa.UUID(), nullable=False),
    sa.Column('responsavel_financeiro', sa.Boolean(), nullable=True),
    sa.Column('parentesco', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsaveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cobranças',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('responsavel_id', sa.UUID(), nullable=False),
    sa.Column('mes_referencia', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('mensalidade', 'matricula', 'rescisao', name='tipo_cobranca'), nullable=False),
    sa.Column('valor_real', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_cheio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'boleto_emitido', 'paga', 'inadimplente', 'cancelada', name='status_cobranca'), nullable=True),
    sa.Column('ciclo_ano', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('forma_pagamento', sa.Enum('boleto', 'dinheiro', name='forma_pagamento'), nullable=True),
    sa.Column('efi_charge_id', sa.String(length=100), nullable=True),
    sa.Column('efi_pix_link', sa.Text(), nullable=True),
    sa.Column('efi_boleto_pdf', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsaveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos_gerados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('dados_utilizados', sa.Text(), nullable=True),
    sa.Column('arquivo_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['templates_documentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('categoria_padrao_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['categoria_padrao_id'], ['categorias_financeiras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lancamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'saida', name='tipo_lancamento'), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('previsto', 'confirmado', 'cancelado', name='status_lancamento'), nullable=True),
    sa.Column('origem', sa.Enum('manual', 'importacao_extrato', 'mensalidade', 'conta_fixa', name='origem_lancamento'), nullable=False),
    sa.Column('efi_transacao_id', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_financeiras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matriculas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.Column('valor_real', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_cheio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('escola', sa.String(length=150), nullable=True),
    sa.Column('serie_escolar', sa.String(length=50), nullable=True),
    sa.Column('ano_letivo', sa.Integer(), nullable=True),
    sa.Column('eh_adulto', sa.Boolean(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('motivo_encerramento', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cobranças_materias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cobranca_id', sa.UUID(), nullable=False),
    sa.Column('matricula_id', sa.UUID(), nullable=False),
    sa.Column('valor_real_materia', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cobranca_id'], ['cobranças.id'], ),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contas_fixas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('frequencia', sa.Enum('mensal', 'bimestral', 'trimestral', 'semestral', 'anual', name='frequencia_conta'), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('fornecedor_id', sa.UUID(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_financeiras.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios_alunos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('matricula_id', sa.UUID(), nullable=False),
    sa.Column('mesa_id', sa.UUID(), nullable=False),
    sa.Column('slot_horario_id', sa.UUID(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], ),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.ForeignKeyConstraint(['slot_horario_id'], ['slots_horario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagens_whatsapp_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('responsavel_id', sa.UUID(), nullable=False),
    sa.Column('cobranca_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('boleto_preventivo', 'cobranca_d1', 'cobranca_d7', 'cobranca_d15', name='tipo_mensagem'), nullable=False),
    sa.Column('status', sa.Enum('enviado', 'erro', name='status_mensagem'), nullable=False),
    sa.Column('erro_detalhes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cobranca_id'], ['cobranças.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsaveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagens_whatsapp_log')
    op.drop_table('horarios_alunos')
    op.drop_table('contas_fixas')
    op.drop_table('cobranças_materias')
    op.drop_table('matriculas')
    op.drop_table('lancamentos')
    op.drop_table('fornecedores')
    op.drop_table('documentos_gerados')
    op.drop_table('cobranças')
    op.drop_table('alunos_responsaveis')
    op.drop_table('templates_documentos')
    op.drop_table('slots_horario')
    op.drop_table('responsaveis')
    op.drop_table('mesas')
    op.drop_table('materias')
    op.drop_table('configuracoes_whatsapp')
    op.drop_table('categorias_financeiras')
    op.drop_table('alunos')
    # ### end Alembic commands ###
