from app.models.aluno import Aluno
from app.models.responsavel import Responsavel
from app.models.aluno_responsavel import AlunoResponsavel
from app.models.materia import Materia
from app.models.matricula import Matricula
from app.models.mesa import Mesa
from app.models.slot_horario import SlotHorario
from app.models.horario_aluno import HorarioAluno
from app.models.categoria import CategoriaFinanceira
from app.models.fornecedor import Fornecedor
from app.models.conta_fixa import ContaFixa
from app.models.lancamento import Lancamento
from app.models.cobranca import Cobranca
from app.models.cobranca_materia import CobrancaMateria
from app.models.template_documento import TemplateDocumento
from app.models.documento_gerado import DocumentoGerado
from app.models.configuracao_whatsapp import ConfiguracaoWhatsapp
from app.models.mensagem_log import MensagemLog